#!/bin/bash

# --- Konfiguracja ---
# Pobierz absolutną ścieżkę do katalogu, w którym znajduje się ten skrypt
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
# Ścieżka do folderu z ikonami (względna lub absolutna)
ICONS_DIR="$SCRIPT_DIR/../assets/icons" 
# Ścieżka do pliku wyjściowego
OUTPUT_FILE="$SCRIPT_DIR/../shared/types/iconsNamesUnion.ts" 
# Nazwa generowanego typu unii
TYPE_NAME="IconName" 
# Dozwolone rozszerzenia (format: *.ext). Pusta lista oznacza wszystkie pliki.
# Użyj spacji jako separatora, np. "*.svg *.png"
ALLOWED_EXTENSIONS="*.svg" 
# --------------------

# Sprawdź, czy folder z ikonami istnieje
if [ ! -d "$ICONS_DIR" ]; then
  echo "❌ Błąd: Folder ikon '$ICONS_DIR' nie istnieje."
  echo "   Bieżący katalog roboczy: $(pwd)"
  echo "   Katalog skryptu: $SCRIPT_DIR"
  exit 1
fi

# Przygotuj argumenty dla find na podstawie rozszerzeń
find_args=()
if [ -n "$ALLOWED_EXTENSIONS" ]; then
  first_ext=true
  for ext in $ALLOWED_EXTENSIONS; do
    if $first_ext; then
      find_args+=(-name "$ext")
      first_ext=false
    else
      find_args+=(-o -name "$ext")
    fi
  done
  # Dodaj nawiasy, jeśli jest więcej niż jedno rozszerzenie lub tylko jedno
  if ! $first_ext; then
     find_args=("(" "${find_args[@]}" ")")
  fi
fi

# Znajdź pliki, wyodrębnij nazwy bazowe bez rozszerzeń i posortuj
# -maxdepth 1: tylko w bieżącym katalogu
# -type f: tylko pliki
# xargs -I {}: wykonaj basename dla każdego znalezionego pliku
# sed 's/\.[^.]*$//': usuń ostatnią kropkę i wszystko po niej (rozszerzenie)
# sort: posortuj nazwy alfabetycznie
icon_names=$(find "$ICONS_DIR" -maxdepth 1 -type f "${find_args[@]}" -print0 | xargs -0 -I {} basename {} | sed 's/\.[^.]*$//' | sort)

# Sprawdź, czy znaleziono jakieś ikony
if [ -z "$icon_names" ]; then
  echo "⚠️ Ostrzeżenie: Nie znaleziono pasujących plików ikon w '$ICONS_DIR'."
  type_content="never"
else
  # Przygotuj zawartość typu: 'name1' | 'name2' | ...
  # paste -sd '|' dodaje '|' między liniami
  # sed 's/^/\x27/; s/$/\x27/; s/|/\x27 | \x27/g' dodaje apostrofy i spacje wokół |
  type_content=$(echo "$icon_names" | paste -sd '|' | sed "s/^/\x27/; s/$/\x27/; s/|/\x27 | \x27/g")
fi

# Wygeneruj pełną definicję typu
output_content="// Auto-generated by Bash script. Do not edit manually.

export type ${TYPE_NAME} = ${type_content};
"

# Zapisz do pliku wyjściowego, nadpisując go
echo "$output_content" > "$OUTPUT_FILE"

echo "✅ Typ unii '${TYPE_NAME}' został wygenerowany w pliku: $OUTPUT_FILE"

exit 0